export const FETCH_ALL_PRODUCT = 'FETCH_ALL_PRODUCT'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT'
export const FETCH_PRODUCT_BY_ID = 'FETCH_PRODUCT_BY_ID'
export const RECEIVE_PRODUCT_DETAIL = 'RECEIVE_PRODUCT_DETAIL'

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const GET_CART_ID = 'GET_CART_ID'

export const FETCH_ALL_ORDER = 'FETCH_ALL_ORDER'
export const ADD_ORDER = 'ADD_ORDER'
export const RECEIVE_ORDER = 'RECEIVE_ORDER'

// CUSTOMER CONSTANTS 
export const CREATE_CUSTOMER_REQUEST = 'CREATE_CUSTOMER_REQUEST'
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS'
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'
export const CREATE_CUSTOMER_FAILURE = 'CREATE_CUSTOMER_FAILURE'

export const CUSTOMER_LOGIN_REQUEST = 'CUSTOMER_LOGIN_REQUEST'
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS'
export const CUSTOMER_LOGIN_FAILURE = 'CUSTOMER_LOGIN_FAILURE'

export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE'

export const CUSTOMER_LOGOUT_REQUEST = 'CUSTOMER_LOGOUT_REQUEST'
export const CUSTOMER_LOGOUT_SUCCESS = 'CUSTOMER_LOGOUT_SUCCESS'

export const FETCH_CART_ITEMS_REQUEST = 'FETCH_CART_ITEMS_REQUEST'
export const FETCH_CART_ITEMS_SUCCESS = 'FETCH_CART_ITEMS_SUCCESS'
export const FETCH_CART_ITEMS_FAILURE = 'FETCH_CART_ITEMS_FAILURE'
export const FETCH_CART_TOTAL_AMOUNT = 'FETCH_CART_TOTAL_AMOUNT'

export const ADD_PRODUCT_REVIEW_REQUEST = 'ADD_PRODUCT_REVIEW_REQUEST'
export const ADD_PRODUCT_REVIEW_SUCCESS = 'ADD_PRODUCT_REVIEW_SUCCESS'
export const ADD_PRODUCT_REVIEW_FAILURE = 'ADD_PRODUCT_REVIEW_FAILURE'

export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST'
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'

export const FETCH_DEPARTMENT_REQUEST = 'FETCH_DEPARTMENT_REQUEST'
export const FETCH_DEPARTMENT_FAILURE = 'FETCH_DEPARTMENT_FAILURE'
export const FETCH_DEPARTMENT_SUCCESS = 'FETCH_DEPARTMENT_SUCCESS'

export const CUSTOMER_SHIPPING_REGIONS_REQUEST = 'CUSTOMER_SHIPPING_REGIONS_REQUEST'
export const CUSTOMER_SHIPPING_REGIONS_SUCCESS = 'CUSTOMER_SHIPPING_REGIONS_SUCCESS'
export const CUSTOMER_SHIPPING_REGIONS_FAILURE = 'CUSTOMER_SHIPPING_REGIONS_FAILURE'
//fetch product reveiws
export const FETCH_PRODUCT_REVIEW_SUCCESS = 'FETCH_PRODUCT_REVIEW_SUCCESS'

